---

sudo: required

dist: xenial

language: generic

python: 2.7

before_install:
  - sudo useradd lowks
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - ls -al /home/travis/miniconda2/bin/
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - echo $PATH
  - conda update --yes conda
install:
   # - sudo apt-get install python-apt
   - conda install --yes python
   - conda install --yes -c anaconda-cluster python-apt
   - conda install --yes -c bioconda ansible
   - ls -al
   - cat ~/.bashrc
script:
  - "ansible-playbook -vv -i localhost development.yml --connection=local --syntax-check"
  # - "ansible-playbook -vv development.yml --connection=local --sudo"
