---
- hosts: localhost
  remote_user: root
  vars:
     vundle_install_path: "/home/lowks/.vim/bundle"
     emacs_path: "/home/lowks/.emacs.d"
  tasks:
    # Add ppa apt repo
    - name: add ppas
      apt_repository: repo={{ item }}
                      update_cache=yes
      with_items:
        - ppa:nilarimogard/webupd8
        - ppa:aacebedo/fasd

    - name: apt-get update
      apt: update_cache=yes cache_valid_time=0

    # Install dependencies
    - name: Install dependencies
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
       - vim-nox
       - git
       - git-crypt
       - python-dev
       - emacs24
       - build-essential
       - zsh
       - python-virtualenv
       - terminator
       - albert
       - tasksel
       - libpq-dev
       - docker.io
       - silversearcher-ag
       - terminology
       - fasd
      # become_method: sudo
      # become: yes
      # become_user: root

    # Create .ssh directory
    - name: Create ssh directory
      file: path=/home/lowks/.ssh state=directory owner=lowks group=lowks

    # Create ssh key
    - user: name=lowks generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=/home/lowks/.ssh/id_rsa

    # Create editor directories
    - name: Create vim directory
      file: path=/home/lowks/.vim/bundle state=directory owner=lowks group=lowks

    # Create project directories
    - name: Create project directories
      file: path=/home/lowks/Projects/ state=directory owner=lowks group=lowks

    # Get Vundle
    - name: Get vundle directories
      # git: repo=git@github.com:VundleVim/Vundle.vim.git
      git: repo=https://github.com/VundleVim/Vundle.vim.git
           dest={{ vundle_install_path }}/Vundle.vim
           version=master
           accept_hostkey=yes
      become: yes
      become_user: lowks
           # key_file=/home/lowks/.ssh/id_rsa

    # Get qemacs
    - name: Get qemacs
      # git: repo=git@github.com:lowks/qemacs.git
      git: repo=https://github.com/lowks/qemacs.git
           accept_hostkey=yes
           version=master
           dest=/tmp/qemacs
           # key_file=/home/lowks/.ssh/id_rsa

    # Get prezto
    - name: Get Prezto
    # git: repo=git@github.com:sorin-ionescu/prezto.git dest=/home/{{ ansible_user_id }}/.zprezto
    #  git: repo=git@github.com:sorin-ionescu/prezto.git dest=/tmp/prezto
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=/home/lowks/.zprezto
           recursive=yes
           version=master
           update=no
           # key_file=/home/lowks/.ssh/id_rsa

    # Link to the .zprezto zshrc
    - name: Link to .zprezto zshrc
      file: src=/home/lowks/.zprezto/runcoms/zshrc dest=/home/lowks/.zshrc state=link

    # Copy over qemacs to Downloads
    - name: Copy over qemacs
      copy: src=/tmp/qemacs/.emacs.d dest=/home/{{ ansible_user_id }}/

    # Do docker tasks
    - include: tasks/docker.yml

    # Do docker tasks
    - include: tasks/install_conda.yml
