---
- hosts: localhost
  remote_user: root
  vars:
     vundle_install_path: "/home/lowks/.vim/bundle"
     emacs_path: "/home/lowks/.emacs.d"
  tasks:
    # Add apt repo for albert
    - name: add ppa for albert
      apt_repository: repo='ppa:nilarimogard/webupd8'
      
    # Install dependencies
    - name: Install dependencies
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
       - vim-nox
       - git
       # - git-crypt
       - python-dev
       # - emacs24
       - build-essential
       - zsh
       - python-virtualenv
       - terminator
       - albert
       - tasksel
       - libpq-dev
      become_method: sudo
      become: yes
      become_user: root

    # Create editor directories
    - name: Create vim directory
      file: path=/home/lowks/.vim/bundle state=directory owner=lowks group=lowks
      
    # Create project directories
    - name: Create project directories
      file: path=/home/lowks/Projects/ state=directory owner=lowks group=lowks

    # Get Vundle
    - name: Get vundle directories
      git: repo=git@github.com:VundleVim/Vundle.vim.git
           dest={{ vundle_install_path }}/Vundle.vim
           accept_hostkey=yes
           key_file=/home/lowks/.ssh/id_rsa

    # Get qemacs
    - name: Get qemacs
      git: repo=git@github.com:lowks/qemacs.git
           dest=/tmp/qemacs
           key_file=/home/lowks/.ssh/id_rsa

    # Get prezto
    - name: Get Prezto
    # git: repo=git@github.com:sorin-ionescu/prezto.git dest=/home/{{ ansible_user_id }}/.zprezto
      git: repo=git@github.com:sorin-ionescu/prezto.git dest=/tmp/prezto
           recursive=yes
           update=no
           key_file=/home/lowks/.ssh/id_rsa

    # Copy over qemacs to Downloads
    - name: Copy over qemacs
      copy: src=/tmp/qemacs/.emacs.d dest=/home/{{ ansible_user_id }}/

    # Do docker tasks
    - include: tasks/docker.yml
