   # - name: Install Nginx
     # become_method: sudo
     # become: yes
     # become_user: root
     # group: name=docker state=present 
     # tags: docker

   - name: Add lowks to docker group
     # become_method: sudo
     # become: yes
     # become_user: root
     user: name=lowks groups=docker append=yes

